---
  - name: import RHEL7 or CentOS 7
    include: RHEL7.yml 
    when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"

  - name: import RHEL6 or CentOS6
    include: RHEL6.yml 
    when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "6"



